name: manager_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  cached_network_image: ^3.4.0
  intl: any
  rxdart: ^0.27.7
  permission_handler: ^10.0.1
  json_annotation: ^4.3.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.0
  flutter_secure_storage: ^8.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  path: ^1.8.2
  flutter_easyloading: ^3.0.5
  # flutter_persistent_keyboard_height: ^1.0.5
  device_info_plus: ^9.0.2
  jiffy: ^6.2.1
  flutter_dotenv: ^5.1.0
  video_player: ^2.8.6
  image_picker: ^1.0.5
  url_launcher: ^6.1.14
  loadmore: ^2.1.0
  uuid: ^4.2.2
  # photo_manager: 2.8.1
  easy_localization: ^3.0.7
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  injectable: ^2.4.2
  dartx: ^1.2.0
  auto_route: ^8.3.0
  vector_graphics: ^1.1.11+1
  path_drawing: ^1.0.1
  flutter_config: ^2.0.2
  flutter_local_notifications: ^17.2.2
  local_auth: ^2.3.0
  webview_flutter: ^4.8.0
  connectivity_plus: ^6.0.5
  flutter_linkify: ^6.0.0
  pinput: ^5.0.0
  logger: ^2.4.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_sms:
    git:
      url: https://github.com/fluttercommunity/flutter_sms.git
      ref: master
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.1
  page_view_dot_indicator: ^2.3.0
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true
  fullscreen: true 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: any
  build_runner: any
  retrofit_generator: 8.1.2
  flutter_gen_runner: ^5.6.0
  auto_route_generator: ^8.1.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    - assets/lang/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/colors/
    - assets/images/logo.png
    - assets/images/booking.png
    - assets/images/take_a_table.png
    - assets/images/icon_arrow.png
    - assets/images/icon_table.png
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    fonts: true
  colors:
    inputs:
      - assets/colors/colors.xml